import { test } from 'node:test';
import assert from 'node:assert/strict';
import { historySince, historySearchPattern, resolveHistoryLocation, HISTORY_PAGE_SIZE, type ReadingHistoryEntry } from '../src/domain/readingHistory.ts';
import type { SourceChapter } from '../src/integrations/sources/types.ts';
const entry: ReadingHistoryEntry = { id: 1, user_id: 'owner', canonical_manga_id: 110, canonical_chapter_key: '5', chapter_number: '5', manga_title: 'Solo Leveling', manga_author: null, cover_image: null, page_index: 1, total_pages: 6, provider: 'asurascans', provider_manga_id: 'obsolete', provider_chapter_id: 'gone', language: 'fr', started_at: '2026-09-08T12:00:00Z', read_at: '2026-09-08T12:05:00Z', updated_at: '2026-09-08T12:05:00Z' };
const candidates = [{ sourceId: 'asurascans', sourceMangaId: 'asura', language: 'en', eligible: true }, { sourceId: 'originmanga', sourceMangaId: 'origin', language: 'fr', eligible: true }];
const chapter: SourceChapter = { id: 'current', source: 'originmanga', chapterNumber: '05.0', title: null, date: '', language: 'fr' };
test('all period has no cutoff', () => assert.equal(historySince('all'), null));
test('today begins at local midnight', () => { const now = new Date(2026, 8, 8, 14); assert.equal(historySince('today', now), new Date(2026, 8, 8).toISOString()); });
test('7 days preserves time of day', () => assert.equal(historySince('7', new Date('2026-09-08T12:00Z')), '2026-09-01T12:00:00.000Z'));
test('30 days crosses month boundaries', () => assert.equal(historySince('30', new Date('2026-09-08T12:00Z')), '2026-08-09T12:00:00.000Z'));
test('search escapes SQL wildcards', () => assert.equal(historySearchPattern('  100%_  '), '%100\\%\\_%'));
test('bounded first page', () => assert.equal(HISTORY_PAGE_SIZE, 25));
test('reopen resolves logical chapter and preserves exact saved page', async () => { const url = await resolveHistoryLocation(entry, candidates, async () => [chapter]); assert.match(url!, /current\?lang=fr&page=1&title=Solo/); assert.equal(new URL(url!, 'https://test').searchParams.get('page'), '1'); });
test('disappeared source falls back to canonical compatible source', async () => { const url = await resolveHistoryLocation(entry, candidates, async c => { if(c.sourceId === 'asurascans') throw new Error('gone'); return [chapter]; }); assert.match(url!, /^\/read\/originmanga\/origin\/current/); });
test('never substitutes a different logical chapter', async () => assert.equal(await resolveHistoryLocation(entry, candidates, async () => [{...chapter, chapterNumber:'6'}]), null));
test('ineligible candidates are never contacted', async () => { let calls = 0; assert.equal(await resolveHistoryLocation(entry, candidates.map(c=>({...c,eligible:false})), async()=>{ calls++; return [chapter]; }),null); assert.equal(calls,0); });
test('page zero is preserved', async () => assert.match((await resolveHistoryLocation({...entry,page_index:0},candidates,async()=>[chapter]))!, /page=0/));
test('reopen does not mutate historical snapshot', async () => { const before = structuredClone(entry); await resolveHistoryLocation(entry,candidates,async()=>[chapter]); assert.deepEqual(entry,before); });
