-- Schéma applicatif Manga Wave : catalogue local et données de lecture par utilisateur.
-- Les tables publiques de contenu restent lisibles, tandis que les données personnelles
-- sont strictement filtrées avec auth.uid() par les politiques RLS.

create table if not exists public.mangas (
  id bigint generated by default as identity primary key,
  title text not null,
  author text,
  description text,
  cover_image text,
  rating numeric(3, 2) check (rating is null or (rating >= 0 and rating <= 10)),
  views bigint not null default 0 check (views >= 0),
  status text not null default 'ongoing' check (status in ('ongoing', 'completed', 'hiatus', 'cancelled')),
  genre text[] not null default '{}',
  manga_type text,
  created_at timestamptz not null default now()
);

create table if not exists public.chapters (
  id bigint generated by default as identity primary key,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  chapter_number numeric(10, 3) not null,
  title text,
  pages_count integer check (pages_count is null or pages_count >= 0),
  release_date timestamptz,
  created_at timestamptz not null default now(),
  unique (manga_id, chapter_number)
);

create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  image_url text not null,
  page_number integer not null check (page_number > 0),
  created_at timestamptz not null default now(),
  unique (chapter_id, page_number)
);

create table if not exists public.user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, manga_id)
);

create table if not exists public.user_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  read_at timestamptz not null default now(),
  unique (user_id, chapter_id)
);

create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  page_number integer not null default 1 check (page_number > 0),
  total_pages integer check (total_pages is null or total_pages >= page_number),
  updated_at timestamptz not null default now(),
  unique (user_id, chapter_id)
);

create index if not exists mangas_created_at_idx on public.mangas (created_at desc);
create index if not exists chapters_manga_id_chapter_number_idx on public.chapters (manga_id, chapter_number);
create index if not exists pages_chapter_id_page_number_idx on public.pages (chapter_id, page_number);
create index if not exists user_favorites_user_id_idx on public.user_favorites (user_id);
create index if not exists user_history_user_id_read_at_idx on public.user_history (user_id, read_at desc);
create index if not exists user_progress_user_id_updated_at_idx on public.user_progress (user_id, updated_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_progress_set_updated_at on public.user_progress;
create trigger user_progress_set_updated_at
before update on public.user_progress
for each row execute function public.set_updated_at();

alter table public.mangas enable row level security;
alter table public.chapters enable row level security;
alter table public.pages enable row level security;
alter table public.user_favorites enable row level security;
alter table public.user_history enable row level security;
alter table public.user_progress enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.mangas, public.chapters, public.pages to anon, authenticated;
grant select, insert, update, delete on public.user_favorites, public.user_history, public.user_progress to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "Le catalogue local est lisible publiquement"
on public.mangas for select
to anon, authenticated
using (true);

create policy "Les chapitres sont lisibles publiquement"
on public.chapters for select
to anon, authenticated
using (true);

create policy "Les pages sont lisibles publiquement"
on public.pages for select
to anon, authenticated
using (true);

create policy "Les favoris sont lisibles par leur propriétaire"
on public.user_favorites for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Les favoris sont ajoutés par leur propriétaire"
on public.user_favorites for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Les favoris sont supprimés par leur propriétaire"
on public.user_favorites for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "L'historique est lisible par son propriétaire"
on public.user_history for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "L'historique est ajouté par son propriétaire"
on public.user_history for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "L'historique est mis à jour par son propriétaire"
on public.user_history for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "L'historique est supprimé par son propriétaire"
on public.user_history for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "La progression est lisible par son propriétaire"
on public.user_progress for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "La progression est ajoutée par son propriétaire"
on public.user_progress for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "La progression est modifiée par son propriétaire"
on public.user_progress for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "La progression est supprimée par son propriétaire"
on public.user_progress for delete
to authenticated
using ((select auth.uid()) = user_id);
