-- T-3014: explicit canonical Follow relationship.
-- Existing favorites are initialized once as follows to preserve T-3013 monitoring.

create table if not exists public.user_follows (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  canonical_manga_id bigint not null references public.mangas(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, canonical_manga_id)
);

create index if not exists user_follows_user_id_idx
on public.user_follows (user_id, created_at desc);

drop trigger if exists user_follows_set_updated_at on public.user_follows;
create trigger user_follows_set_updated_at
before update on public.user_follows
for each row execute function public.set_updated_at();

alter table public.user_follows enable row level security;
grant select, insert, delete on public.user_follows to authenticated;

create policy "Follows are visible to their owner"
on public.user_follows for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Follows are created by their owner"
on public.user_follows for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Follows are deleted by their owner"
on public.user_follows for delete to authenticated
using ((select auth.uid()) = user_id);

-- One-time compatibility bridge: current favorite monitoring becomes explicit Follow.
insert into public.user_follows (user_id, canonical_manga_id, created_at, updated_at)
select favorite.user_id, favorite.manga_id, favorite.created_at, now()
from public.user_favorites favorite
on conflict (user_id, canonical_manga_id) do nothing;

-- T-3013 state now belongs to Follow, not Favorite. This also makes Follow-only valid.
do $$
declare
  legacy_constraint text;
begin
  select constraint_row.conname
  into legacy_constraint
  from pg_constraint constraint_row
  join pg_class source_table on source_table.oid = constraint_row.conrelid
  join pg_namespace source_schema on source_schema.oid = source_table.relnamespace
  join pg_class target_table on target_table.oid = constraint_row.confrelid
  join pg_namespace target_schema on target_schema.oid = target_table.relnamespace
  where constraint_row.contype = 'f'
    and source_schema.nspname = 'public'
    and source_table.relname = 'user_followed_chapter_state'
    and target_schema.nspname = 'public'
    and target_table.relname = 'user_favorites'
  limit 1;

  if legacy_constraint is not null then
    execute format(
      'alter table public.user_followed_chapter_state drop constraint %I',
      legacy_constraint
    );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.user_followed_chapter_state'::regclass
      and conname = 'user_followed_chapter_state_follow_fkey'
  ) then
    alter table public.user_followed_chapter_state
      add constraint user_followed_chapter_state_follow_fkey
      foreign key (user_id, manga_id)
      references public.user_follows(user_id, canonical_manga_id)
      on delete cascade;
  end if;
end
$$;
