-- T-3015: canonical in-app notifications generated from T-3013 state.

create table if not exists public.user_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  canonical_manga_id bigint not null references public.mangas(id) on delete cascade,
  canonical_chapter_key text not null,
  type text not null default 'new_chapter' check (type = 'new_chapter'),
  title text not null,
  body text not null,
  chapter_number text not null,
  chapter_title text,
  language text not null default 'und',
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  unique (user_id, canonical_manga_id, canonical_chapter_key, type),
  check ((is_read and read_at is not null) or (not is_read and read_at is null))
);

create index if not exists user_notifications_user_created_idx
on public.user_notifications (user_id, created_at desc);

create index if not exists user_notifications_unread_idx
on public.user_notifications (user_id, created_at desc)
where not is_read;

create index if not exists user_notifications_canonical_manga_idx
on public.user_notifications (canonical_manga_id);

alter table public.user_notifications enable row level security;
revoke all on public.user_notifications from anon, authenticated;
grant select on public.user_notifications to authenticated;
grant update (is_read, read_at) on public.user_notifications to authenticated;

create policy "Notifications are visible to their owner"
on public.user_notifications for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Notification read state is updated by its owner"
on public.user_notifications for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create or replace function public.create_new_chapter_notification()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  manga_title text;
begin
  -- A non-null read_at is T-3013's baseline and must never create history noise.
  if new.read_at is not null then
    return new;
  end if;

  -- Keep Follow as the explicit product gate even if constraints evolve later.
  if not exists (
    select 1
    from public.user_follows follow_row
    where follow_row.user_id = new.user_id
      and follow_row.canonical_manga_id = new.manga_id
  ) then
    return new;
  end if;

  select manga.title into manga_title
  from public.mangas manga
  where manga.id = new.manga_id;

  insert into public.user_notifications (
    user_id,
    canonical_manga_id,
    canonical_chapter_key,
    type,
    title,
    body,
    chapter_number,
    chapter_title,
    language,
    metadata
  ) values (
    new.user_id,
    new.manga_id,
    new.canonical_chapter_key,
    'new_chapter',
    'Nouveau chapitre',
    coalesce(manga_title, 'Manga') || ' — Chapitre ' || new.chapter_number || ' est disponible.',
    new.chapter_number,
    new.chapter_title,
    new.language,
    jsonb_build_object('chapter_number', new.chapter_number, 'language', new.language)
  )
  on conflict (user_id, canonical_manga_id, canonical_chapter_key, type) do nothing;

  return new;
end;
$$;

revoke all on function public.create_new_chapter_notification() from public, anon, authenticated;

drop trigger if exists user_followed_chapter_state_notify_new_chapter
on public.user_followed_chapter_state;
create trigger user_followed_chapter_state_notify_new_chapter
after insert on public.user_followed_chapter_state
for each row execute function public.create_new_chapter_notification();

create or replace function public.acknowledge_chapter_notification()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.read_at is null and new.read_at is not null then
    update public.user_notifications
    set is_read = true, read_at = new.read_at
    where user_id = new.user_id
      and canonical_manga_id = new.manga_id
      and canonical_chapter_key = new.canonical_chapter_key
      and type = 'new_chapter'
      and not is_read;
  end if;
  return new;
end;
$$;

revoke all on function public.acknowledge_chapter_notification() from public, anon, authenticated;

drop trigger if exists user_followed_chapter_state_acknowledge_notification
on public.user_followed_chapter_state;
create trigger user_followed_chapter_state_acknowledge_notification
after update of read_at on public.user_followed_chapter_state
for each row execute function public.acknowledge_chapter_notification();
