-- `mangas` remains the canonical catalogue so existing user foreign keys remain valid.
create extension if not exists pg_trgm with schema extensions;
alter table public.mangas
  add column if not exists normalized_title text,
  add column if not exists aliases text[] not null default '{}',
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists last_synced_at timestamptz;

update public.mangas
set normalized_title = lower(trim(regexp_replace(title, '[^[:alnum:]]+', ' ', 'g')))
where normalized_title is null;

alter table public.mangas alter column normalized_title set not null;
create index if not exists mangas_normalized_title_idx on public.mangas (normalized_title);
create index if not exists mangas_normalized_title_trgm_idx
  on public.mangas using gin (normalized_title extensions.gin_trgm_ops);

create table if not exists public.manga_source_mappings (
  id bigint generated by default as identity primary key,
  manga_id bigint not null references public.mangas(id) on delete cascade,
  source_id text not null,
  source_manga_id text not null,
  source_url text,
  source_title text not null,
  normalized_source_title text not null,
  match_confidence numeric(4, 3) not null default 1 check (match_confidence between 0 and 1),
  manually_verified boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_id, source_manga_id),
  unique (manga_id, source_id)
);

create table if not exists public.chapter_snapshots (
  id bigint generated by default as identity primary key,
  mapping_id bigint not null references public.manga_source_mappings(id) on delete cascade,
  source_chapter_id text not null,
  chapter_number text not null,
  title text,
  language text,
  source_url text,
  page_urls text[] not null default '{}',
  available boolean not null default true,
  fetched_at timestamptz not null default now(),
  expires_at timestamptz,
  unique (mapping_id, source_chapter_id)
);

create table if not exists public.source_health (
  source_id text primary key,
  circuit_state text not null default 'closed' check (circuit_state in ('closed', 'open', 'half-open')),
  score integer not null default 100 check (score between 0 and 100),
  average_latency_ms integer not null default 0 check (average_latency_ms >= 0),
  request_count bigint not null default 0,
  success_count bigint not null default 0,
  failure_count bigint not null default 0,
  consecutive_failures integer not null default 0,
  last_success_at timestamptz,
  last_failure_at timestamptz,
  last_error text,
  retry_at timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.source_health (source_id)
values ('mangadex'), ('comick'), ('originmanga'), ('crunchyscan'), ('mangafire'), ('asurascans')
on conflict (source_id) do nothing;

create index if not exists manga_source_mappings_manga_idx on public.manga_source_mappings (manga_id);
create index if not exists manga_source_mappings_normalized_title_idx on public.manga_source_mappings (normalized_source_title);
create index if not exists chapter_snapshots_mapping_number_idx on public.chapter_snapshots (mapping_id, chapter_number);
create index if not exists chapter_snapshots_expires_idx on public.chapter_snapshots (expires_at);
create index if not exists source_health_score_idx on public.source_health (score desc);

drop trigger if exists mangas_set_updated_at on public.mangas;
create trigger mangas_set_updated_at before update on public.mangas
for each row execute function public.set_updated_at();

drop trigger if exists manga_source_mappings_set_updated_at on public.manga_source_mappings;
create trigger manga_source_mappings_set_updated_at before update on public.manga_source_mappings
for each row execute function public.set_updated_at();

alter table public.manga_source_mappings enable row level security;
alter table public.chapter_snapshots enable row level security;
alter table public.source_health enable row level security;

grant select on public.manga_source_mappings, public.chapter_snapshots, public.source_health to anon, authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "Les mappings de sources sont lisibles publiquement"
on public.manga_source_mappings for select to anon, authenticated using (true);

create policy "Les snapshots de chapitres sont lisibles publiquement"
on public.chapter_snapshots for select to anon, authenticated using (true);

create policy "La santé des sources est lisible publiquement"
on public.source_health for select to anon, authenticated using (true);

create or replace function public.find_canonical_manga(candidate_title text)
returns table (
  manga_id bigint,
  title text,
  confidence numeric,
  match_reason text
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  with candidate as (
    select lower(trim(regexp_replace(candidate_title, '[^[:alnum:]]+', ' ', 'g'))) as normalized
  )
  select
    mangas.id,
    mangas.title,
    case
      when mangas.normalized_title = candidate.normalized then 1::numeric
      when candidate.normalized = any (
        select lower(trim(regexp_replace(alias, '[^[:alnum:]]+', ' ', 'g')))
        from unnest(mangas.aliases) alias
      ) then 0.95::numeric
      else round(similarity(mangas.normalized_title, candidate.normalized)::numeric, 3)
    end as confidence,
    case
      when mangas.normalized_title = candidate.normalized then 'exact_title'
      when candidate.normalized = any (
        select lower(trim(regexp_replace(alias, '[^[:alnum:]]+', ' ', 'g')))
        from unnest(mangas.aliases) alias
      ) then 'exact_alias'
      else 'fuzzy_title'
    end as match_reason
  from public.mangas
  cross join candidate
  where mangas.normalized_title = candidate.normalized
     or candidate.normalized = any (
       select lower(trim(regexp_replace(alias, '[^[:alnum:]]+', ' ', 'g')))
       from unnest(mangas.aliases) alias
     )
     or similarity(mangas.normalized_title, candidate.normalized) >= 0.3
  order by confidence desc, mangas.id
  limit 10;
$$;

grant execute on function public.find_canonical_manga(text) to anon, authenticated;
