create extension if not exists pgmq;

do $$
begin
  if not exists (select 1 from pgmq.meta where queue_name = 'source_sync') then
    perform pgmq.create('source_sync');
  end if;
end;
$$;

create table if not exists public.source_sync_runs (
  id bigint generated by default as identity primary key,
  queue_message_id bigint,
  source_id text not null,
  job_type text not null,
  status text not null default 'running' check (status in ('running', 'succeeded', 'failed')),
  items_synced integer not null default 0,
  attempt integer not null default 1,
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists source_sync_runs_source_started_idx
  on public.source_sync_runs (source_id, started_at desc);

alter table public.source_sync_runs enable row level security;
grant select on public.source_sync_runs to authenticated;

create policy "Les utilisateurs authentifiés consultent les synchronisations"
on public.source_sync_runs for select to authenticated using (true);

create or replace function public.enqueue_source_sync(
  job jsonb,
  delay_seconds integer default 0
)
returns bigint
language sql
security definer
set search_path = public, pgmq
as $$
  select pgmq.send('source_sync', job, greatest(delay_seconds, 0));
$$;

create or replace function public.dequeue_source_sync(
  batch_size integer default 2,
  visibility_seconds integer default 120
)
returns table (
  msg_id bigint,
  read_ct integer,
  enqueued_at timestamptz,
  visible_at timestamptz,
  message jsonb
)
language sql
security definer
set search_path = public, pgmq
as $$
  select queued.msg_id, queued.read_ct, queued.enqueued_at, queued.vt, queued.message
  from pgmq.read('source_sync', greatest(visibility_seconds, 30), least(greatest(batch_size, 1), 6)) queued;
$$;

create or replace function public.complete_source_sync(
  message_id bigint,
  archive_message boolean default false
)
returns boolean
language plpgsql
security definer
set search_path = public, pgmq
as $$
begin
  if archive_message then
    return pgmq.archive('source_sync', message_id);
  end if;
  return pgmq.delete('source_sync', message_id);
end;
$$;

create or replace function public.upsert_source_catalog(
  requested_source_id text,
  items jsonb
)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  item jsonb;
  canonical_id bigint;
  normalized text;
  v_source_manga_id text;
  source_title text;
  source_status text;
  source_rating numeric;
  source_genres text[];
  processed integer := 0;
begin
  if jsonb_typeof(items) <> 'array' then
    raise exception 'items doit être un tableau JSON';
  end if;

  for item in select value from jsonb_array_elements(items)
  loop
    v_source_manga_id := nullif(item->>'id', '');
    source_title := nullif(item->>'title', '');
    if v_source_manga_id is null or source_title is null then
      continue;
    end if;

    normalized := lower(trim(regexp_replace(source_title, '[^[:alnum:]]+', ' ', 'g')));
    source_status := lower(coalesce(item->>'status', 'ongoing'));
    if source_status not in ('ongoing', 'completed', 'hiatus', 'cancelled') then
      source_status := 'ongoing';
    end if;
    source_rating := case
      when coalesce(item->>'rating', '') ~ '^[0-9]+([.][0-9]+)?$' then least((item->>'rating')::numeric, 10)
      else null
    end;
    source_genres := array(
      select jsonb_array_elements_text(coalesce(item->'genres', '[]'::jsonb))
    );

    select mapping.manga_id into canonical_id
    from public.manga_source_mappings mapping
    where mapping.source_id = requested_source_id
      and mapping.source_manga_id = v_source_manga_id;

    if canonical_id is null then
      select manga.id into canonical_id
      from public.mangas manga
      where (
        manga.normalized_title = normalized
        or normalized = any (
           select lower(trim(regexp_replace(alias, '[^[:alnum:]]+', ' ', 'g')))
           from unnest(manga.aliases) alias
        )
      )
      and not exists (
        select 1
        from public.manga_source_mappings existing_mapping
        where existing_mapping.manga_id = manga.id
          and existing_mapping.source_id = requested_source_id
      )
      order by manga.id
      limit 1;
    end if;

    if canonical_id is null then
      insert into public.mangas (
        title, normalized_title, cover_image, status, genre, rating, last_synced_at
      ) values (
        source_title,
        normalized,
        nullif(item->>'coverUrl', ''),
        source_status,
        coalesce(source_genres, '{}'),
        source_rating,
        now()
      ) returning id into canonical_id;
    else
      update public.mangas
      set cover_image = coalesce(cover_image, nullif(item->>'coverUrl', '')),
          genre = case when cardinality(genre) = 0 then coalesce(source_genres, '{}') else genre end,
          last_synced_at = now()
      where id = canonical_id;
    end if;

    insert into public.manga_source_mappings (
      manga_id,
      source_id,
      source_manga_id,
      source_url,
      source_title,
      normalized_source_title,
      match_confidence,
      metadata,
      last_synced_at
    ) values (
      canonical_id,
      requested_source_id,
      v_source_manga_id,
      nullif(item->>'url', ''),
      source_title,
      normalized,
      case when exists (
        select 1 from public.mangas manga
        where manga.id = canonical_id and manga.normalized_title = normalized
      ) then 1 else 0.8 end,
      item,
      now()
    )
    on conflict on constraint manga_source_mappings_source_id_source_manga_id_key do update
      set source_url = excluded.source_url,
          source_title = excluded.source_title,
          normalized_source_title = excluded.normalized_source_title,
          metadata = excluded.metadata,
          last_synced_at = now();

    processed := processed + 1;
  end loop;

  return processed;
end;
$$;

revoke all on function public.enqueue_source_sync(jsonb, integer) from public, anon, authenticated;
revoke all on function public.dequeue_source_sync(integer, integer) from public, anon, authenticated;
revoke all on function public.complete_source_sync(bigint, boolean) from public, anon, authenticated;
revoke all on function public.upsert_source_catalog(text, jsonb) from public, anon, authenticated;

grant execute on function public.enqueue_source_sync(jsonb, integer) to service_role;
grant execute on function public.dequeue_source_sync(integer, integer) to service_role;
grant execute on function public.complete_source_sync(bigint, boolean) to service_role;
grant execute on function public.upsert_source_catalog(text, jsonb) to service_role;
grant select, insert, update on public.source_sync_runs to service_role;
grant usage, select on all sequences in schema public to service_role;

select public.enqueue_source_sync(
  jsonb_build_object('type', 'SYNC_SOURCE', 'source', source_id),
  ((position - 1) * 20)::integer
)
from unnest(array['mangadex', 'comick', 'originmanga', 'crunchyscan', 'mangafire', 'asurascans'])
  with ordinality as initial_jobs(source_id, position);
