// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuebnijezlpyolmwfylx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1ZWJuaWplemxweW9sbXdmeWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzMwMjksImV4cCI6MjA2Njg0OTAyOX0.9e-YdPwcW1ctm1PGKvSgtaS-p1gkL3V3kvuqg1cGPm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});